### ISSUE TITLE
Node 14+ is unsupported!

### ISSUE THREAD

**Issue by alflennik** [sindresorhus/npm-name-cli#28]
Here's the error I got when I tried to run the command on Node 14:

```
file:///Users/alflennik/.nvm/versions/node/v14.5.0/lib/node_modules/npm-name-cli/node_modules/npm-name/index.js:10
import {isTaken} from 'is-name-taken';
        ^^^^^^^
SyntaxError: The requested module 'is-name-taken' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'is-name-taken';
const {isTaken} = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
    at async Loader.import (internal/modules/esm/loader.js:162:24)
```

I reverted to Node 12 and it worked.

Thanks for the package, by the way! It helped me find a great package name.

**Comment by sindresorhus** [comment]
You need a newer Node.js 14 version.
